using System;

namespace YasunliESModel.Models
{
    public partial class Troubleshooting
    {
        public int TroubleShootingId { get; set; }
        public string SPPNo { get; set; }
        public string Defect { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> HEBefore { get; set; }
        public Nullable<decimal> HEAfter { get; set; }
        public Nullable<decimal> HNZBefore { get; set; }
        public Nullable<decimal> HNZAfter { get; set; }
        public Nullable<decimal> H1ZBefore { get; set; }
        public Nullable<decimal> H2ZBefore { get; set; }
        public Nullable<decimal> H3ZBefore { get; set; }
        public Nullable<decimal> H4ZBefore { get; set; }
        public Nullable<decimal> H5Before { get; set; }
        public Nullable<decimal> H6Before { get; set; }
        public Nullable<decimal> H1ZAfter { get; set; }
        public Nullable<decimal> H2ZAfter { get; set; }
        public Nullable<decimal> H3ZAfter { get; set; }
        public Nullable<decimal> H4ZAfter { get; set; }
        public Nullable<decimal> H5After { get; set; }
        public Nullable<decimal> H6After { get; set; }
        public string MTCBefore { get; set; }
        public string MTCAfter { get; set; }
        public Nullable<decimal> PH1ForceBefore { get; set; }
        public Nullable<decimal> PH1ForceAfter { get; set; }
        public Nullable<decimal> PH2ForceBefore { get; set; }
        public Nullable<decimal> PH2ForceAfter { get; set; }
        public Nullable<decimal> PH3ForceBefore { get; set; }
        public Nullable<decimal> PH3ForceAfter { get; set; }
        public Nullable<decimal> PH1TimeBefore { get; set; }
        public Nullable<decimal> PH1TimeAfter { get; set; }
        public Nullable<decimal> PH2TimeBefore { get; set; }
        public Nullable<decimal> PH2TimeAfter { get; set; }
        public Nullable<decimal> VHBefore { get; set; }
        public Nullable<decimal> VHAfter { get; set; }
        public Nullable<decimal> IP3Before { get; set; }
        public Nullable<decimal> IP2Before { get; set; }
        public Nullable<decimal> IP1Before { get; set; }
        public Nullable<decimal> IP3After { get; set; }
        public Nullable<decimal> IP2After { get; set; }
        public Nullable<decimal> IP1After { get; set; }
        public Nullable<decimal> IV4Before { get; set; }
        public Nullable<decimal> IV3Before { get; set; }
        public Nullable<decimal> IV2Before { get; set; }
        public Nullable<decimal> IV1Before { get; set; }
        public Nullable<decimal> IV4After { get; set; }
        public Nullable<decimal> IV3After { get; set; }
        public Nullable<decimal> IV2After { get; set; }
        public Nullable<decimal> IV1After { get; set; }
        public Nullable<decimal> MTCavityBefore { get; set; }
        public Nullable<decimal> MTCavityAfter { get; set; }
        public Nullable<decimal> MTCoreBefore { get; set; }
        public Nullable<decimal> MTCoreAfter { get; set; }
        public Nullable<decimal> INJTimeBefore { get; set; }
        public Nullable<decimal> INJTimeAfter { get; set; }
        public Nullable<decimal> VSB1Before { get; set; }
        public Nullable<decimal> VSB1After { get; set; }
        public Nullable<decimal> RPM1Before { get; set; }
        public Nullable<decimal> RPM2Before { get; set; }
        public Nullable<decimal> RPM3Before { get; set; }
        public Nullable<decimal> RPM1After { get; set; }
        public Nullable<decimal> RPM2After { get; set; }
        public Nullable<decimal> RPM3After { get; set; }
        public Nullable<decimal> VSB2Before { get; set; }
        public Nullable<decimal> VSB2After { get; set; }
        public Nullable<decimal> CoolingBefore { get; set; }
        public Nullable<decimal> CoolingAfter { get; set; }
        public Nullable<decimal> CHGDlyBefore { get; set; }
        public Nullable<decimal> CHGDlyAfter { get; set; }
        public Nullable<decimal> GP1Before { get; set; }
        public Nullable<decimal> GP2Before { get; set; }
        public Nullable<decimal> GP3Before { get; set; }
        public Nullable<decimal> GP4Before { get; set; }
        public Nullable<decimal> GP5Before { get; set; }
        public Nullable<decimal> GP1After { get; set; }
        public Nullable<decimal> GP2After { get; set; }
        public Nullable<decimal> GP3After { get; set; }
        public Nullable<decimal> GP4After { get; set; }
        public Nullable<decimal> GP5After { get; set; }
        public Nullable<decimal> GT1Before { get; set; }
        public Nullable<decimal> GT2Before { get; set; }
        public Nullable<decimal> GT3Before { get; set; }
        public Nullable<decimal> GT4Before { get; set; }
        public Nullable<decimal> GT5Before { get; set; }
        public Nullable<decimal> GT1After { get; set; }
        public Nullable<decimal> GT2After { get; set; }
        public Nullable<decimal> GT3After { get; set; }
        public Nullable<decimal> GT4After { get; set; }
        public Nullable<decimal> GT5After { get; set; }
        public Nullable<decimal> GD1Before { get; set; }
        public Nullable<decimal> GD2Before { get; set; }
        public Nullable<decimal> GD3Before { get; set; }
        public Nullable<decimal> GD4Before { get; set; }
        public Nullable<decimal> GD5Before { get; set; }
        public Nullable<decimal> GD1After { get; set; }
        public Nullable<decimal> GD2After { get; set; }
        public Nullable<decimal> GD3After { get; set; }
        public Nullable<decimal> GD4After { get; set; }
        public Nullable<decimal> GD5After { get; set; }
        public Nullable<decimal> ChusionBefore { get; set; }
        public Nullable<decimal> ShotSizeBefore { get; set; }
        public Nullable<decimal> CycleTimeBefore { get; set; }
        public Nullable<decimal> MmMDClsBefore { get; set; }
        public Nullable<decimal> MmMDOpnTBefore { get; set; }
        public Nullable<decimal> FillTimeBefore { get; set; }
        public Nullable<decimal> InjtTimeBefore { get; set; }
        public Nullable<decimal> ChgeTimeBefore { get; set; }
        public Nullable<decimal> IntTimeBefore { get; set; }
        public Nullable<decimal> IntTimeAfter { get; set; }
        public Nullable<decimal> VO3Before { get; set; }
        public Nullable<decimal> VO2Before { get; set; }
        public Nullable<decimal> VO1Before { get; set; }
        public Nullable<decimal> VOHBefore { get; set; }
        public Nullable<decimal> VO3After { get; set; }
        public Nullable<decimal> VO2After { get; set; }
        public Nullable<decimal> VO1After { get; set; }
        public Nullable<decimal> VOHAfter { get; set; }
        public Nullable<decimal> VC1Before { get; set; }
        public Nullable<decimal> VC2Before { get; set; }
        public Nullable<decimal> VC1After { get; set; }
        public Nullable<decimal> VC2After { get; set; }
        public Nullable<decimal> PCLBefore { get; set; }
        public Nullable<decimal> PCLAfter { get; set; }
        public Nullable<decimal> PCHBefore { get; set; }
        public Nullable<decimal> PCHAfter { get; set; }
        public Nullable<decimal> VR2Before { get; set; }
        public Nullable<decimal> VR1Before { get; set; }
        public Nullable<decimal> VR2After { get; set; }
        public Nullable<decimal> VR1After { get; set; }
        public Nullable<decimal> PERBefore { get; set; }
        public Nullable<decimal> PERAfter { get; set; }
        public Nullable<decimal> VF1Before { get; set; }
        public Nullable<decimal> VF2Before { get; set; }
        public Nullable<decimal> VF3Before { get; set; }
        public Nullable<decimal> VF1After { get; set; }
        public Nullable<decimal> VF2After { get; set; }
        public Nullable<decimal> VF3After { get; set; }
        public Nullable<decimal> PEFBefore { get; set; }
        public Nullable<decimal> PEFAfter { get; set; }
        public Nullable<decimal> GateD1Before { get; set; }
        public Nullable<decimal> GateD2Before { get; set; }
        public Nullable<decimal> GateD3Before { get; set; }
        public Nullable<decimal> GateD4Before { get; set; }
        public Nullable<decimal> GateD5Before { get; set; }
        public Nullable<decimal> GateD6Before { get; set; }
        public Nullable<decimal> GateD1After { get; set; }
        public Nullable<decimal> GateD2After { get; set; }
        public Nullable<decimal> GateD3After { get; set; }
        public Nullable<decimal> GateD4After { get; set; }
        public Nullable<decimal> GateD5After { get; set; }
        public Nullable<decimal> GateD6After { get; set; }
        public Nullable<decimal> GateO1Before { get; set; }
        public Nullable<decimal> GateO2Before { get; set; }
        public Nullable<decimal> GateO3Before { get; set; }
        public Nullable<decimal> GateO4Before { get; set; }
        public Nullable<decimal> GateO5Before { get; set; }
        public Nullable<decimal> GateO6Before { get; set; }
        public Nullable<decimal> GateO1After { get; set; }
        public Nullable<decimal> GateO2After { get; set; }
        public Nullable<decimal> GateO3After { get; set; }
        public Nullable<decimal> GateO4After { get; set; }
        public Nullable<decimal> GateO5After { get; set; }
        public Nullable<decimal> GateO6After { get; set; }
        public Nullable<decimal> GateT1Before { get; set; }
        public Nullable<decimal> GateT2Before { get; set; }
        public Nullable<decimal> GateT3Before { get; set; }
        public Nullable<decimal> GateT4Before { get; set; }
        public Nullable<decimal> GateT5Before { get; set; }
        public Nullable<decimal> GateT6Before { get; set; }
        public Nullable<decimal> GateT1After { get; set; }
        public Nullable<decimal> GateT2After { get; set; }
        public Nullable<decimal> GateT3After { get; set; }
        public Nullable<decimal> GateT4After { get; set; }
        public Nullable<decimal> GateT5After { get; set; }
        public Nullable<decimal> GateT6After { get; set; }
        public Nullable<decimal> CoreNo { get; set; }
        public string Jenis { get; set; }
        public Nullable<decimal> TimerIn { get; set; }
        public Nullable<decimal> TimerOut { get; set; }
        public Nullable<decimal> SPBefore { get; set; }
        public Nullable<decimal> SPAfter { get; set; }
        public Nullable<decimal> LS4DBefore { get; set; }
        public Nullable<decimal> LS4CBefore { get; set; }
        public Nullable<decimal> LS4BBefore { get; set; }
        public Nullable<decimal> LS4ABefore { get; set; }
        public Nullable<decimal> LS4DAfter { get; set; }
        public Nullable<decimal> LS4CAfter { get; set; }
        public Nullable<decimal> LS4BAfter { get; set; }
        public Nullable<decimal> LS4AAfter { get; set; }
        public Nullable<decimal> L10ABefore { get; set; }
        public Nullable<decimal> L10AAfter { get; set; }
        public Nullable<decimal> LS5BBefore { get; set; }
        public Nullable<decimal> LS5ABefore { get; set; }
        public Nullable<decimal> LS5Before { get; set; }
        public Nullable<decimal> LS5BAfter { get; set; }
        public Nullable<decimal> LS5AAfter { get; set; }
        public Nullable<decimal> LS5After { get; set; }
        public Nullable<decimal> L10BBefore { get; set; }
        public Nullable<decimal> L10BAfter { get; set; }
        public Nullable<decimal> LS31ABefore { get; set; }
        public Nullable<decimal> LS31BBefore { get; set; }
        public Nullable<decimal> LS31Before { get; set; }
        public Nullable<decimal> LS31AAfter { get; set; }
        public Nullable<decimal> LS31BAfter { get; set; }
        public Nullable<decimal> LS31After { get; set; }
        public Nullable<decimal> LS32ABefore { get; set; }
        public Nullable<decimal> LS32BBefore { get; set; }
        public Nullable<decimal> LS32AAfter { get; set; }
        public Nullable<decimal> LS32BAfter { get; set; }
        public Nullable<decimal> LS2BBefore { get; set; }
        public Nullable<decimal> LS2ABefore { get; set; }
        public Nullable<decimal> LS2Before { get; set; }
        public Nullable<decimal> LS2BAfter { get; set; }
        public Nullable<decimal> LS2AAfter { get; set; }
        public Nullable<decimal> LS2After { get; set; }
        public Nullable<decimal> LS3Before { get; set; }
        public Nullable<decimal> LS3BBefore { get; set; }
        public Nullable<decimal> LS3ABefore { get; set; }
        public Nullable<decimal> LS3MBefore { get; set; }
        public Nullable<decimal> LS3After { get; set; }
        public Nullable<decimal> LS3BAfter { get; set; }
        public Nullable<decimal> LS3AAfter { get; set; }
        public Nullable<decimal> LS3MAfter { get; set; }
        public Nullable<decimal> ChushionAfter { get; set; }
        public Nullable<decimal> ShotsizeAfter { get; set; }
        public Nullable<decimal> CycleTimeAfter { get; set; }
        public Nullable<decimal> MmMDClsAfter { get; set; }
        public Nullable<decimal> MmMDOpnTAfter { get; set; }
        public Nullable<decimal> FillTimeAfter { get; set; }
        public Nullable<decimal> InjtTimeAfter { get; set; }
        public Nullable<decimal> ChgeTimeAfter { get; set; }
        public Nullable<decimal> VGOpen1Before { get; set; }
        public Nullable<decimal> VGOpen1After { get; set; }
        public Nullable<decimal> VGOpen2Before { get; set; }
        public Nullable<decimal> VGOpen2After { get; set; }
        public Nullable<decimal> VGOpen3Before { get; set; }
        public Nullable<decimal> VGOpen3After { get; set; }
        public Nullable<decimal> VGOpen4Before { get; set; }
        public Nullable<decimal> VGOpen4After { get; set; }
        public Nullable<decimal> VGOpen5Before { get; set; }
        public Nullable<decimal> VGOpen5After { get; set; }
        public Nullable<decimal> VGOpen6Before { get; set; }
        public Nullable<decimal> VGOpen6After { get; set; }
        public Nullable<decimal> VGDelay1Before { get; set; }
        public Nullable<decimal> VGDelay1After { get; set; }
        public Nullable<decimal> VGDelay2Before { get; set; }
        public Nullable<decimal> VGDelay2After { get; set; }
        public Nullable<decimal> VGDelay3Before { get; set; }
        public Nullable<decimal> VGDelay3After { get; set; }
        public Nullable<decimal> VGDelay4Before { get; set; }
        public Nullable<decimal> VGDelay4After { get; set; }
        public Nullable<decimal> VGDelay5Before { get; set; }
        public Nullable<decimal> VGDelay5After { get; set; }
        public Nullable<decimal> VGDelay6Before { get; set; }
        public Nullable<decimal> VGDelay6After { get; set; }
        public Nullable<decimal> BP1Before { get; set; }
        public Nullable<decimal> BP1After { get; set; }
        public Nullable<decimal> BP2Before { get; set; }
        public Nullable<decimal> BP2After { get; set; }
        public Nullable<decimal> BP3Before { get; set; }
        public Nullable<decimal> BP3After { get; set; }
        public Nullable<decimal> HR1Before { get; set; }
        public Nullable<decimal> HR1After { get; set; }
        public Nullable<decimal> HR2Before { get; set; }
        public Nullable<decimal> HR2After { get; set; }
        public Nullable<decimal> HR3Before { get; set; }
        public Nullable<decimal> HR3After { get; set; }
        public Nullable<decimal> HR4Before { get; set; }
        public Nullable<decimal> HR4After { get; set; }
        public Nullable<decimal> HR5Before { get; set; }
        public Nullable<decimal> HR5After { get; set; }
        public Nullable<decimal> HR6Before { get; set; }
        public Nullable<decimal> HR6After { get; set; }
        public Nullable<decimal> HR7Before { get; set; }
        public Nullable<decimal> HR7After { get; set; }
        public Nullable<decimal> HR8Before { get; set; }
        public Nullable<decimal> HR8After { get; set; }
        public Nullable<decimal> HR9Before { get; set; }
        public Nullable<decimal> HR9After { get; set; }
        public Nullable<decimal> HR10Before { get; set; }
        public Nullable<decimal> HR10After { get; set; }
        public Nullable<decimal> HR11Before { get; set; }
        public Nullable<decimal> HR11After { get; set; }
        public Nullable<decimal> HR12Before { get; set; }
        public Nullable<decimal> HR12After { get; set; }
        public Nullable<System.DateTime> SettingTime { get; set; }
        public Nullable<decimal> QTYNG { get; set; }
        public Nullable<decimal> QTYTotal { get; set; }
        public Nullable<decimal> IP4Before { get; set; }
        public Nullable<decimal> IP4After { get; set; }
    }
}
